### ISSUE TITLE
Delete Commandtpo.java

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TF-Essentials#12]
Remove TPO

**Comment by OnlineRepz** [comment]
Sound a good idea, however, we should limit it to admins, so they can override tpo to players to check for griefs and others.

**Comment by DUFCLiam** [comment]
I thought that so we can TPO to rule breakers

**Comment by OnlineRepz** [comment]
@DUFCLiam, if we need to limit it to admins, this should be on TFM side

**Comment by JeromSar** [comment]
No /tpo is handy.
