### ISSUE TITLE
Fix permissions for using colorcodes in chat.

### ISSUE THREAD

**Issue by aokod** [TotalFreedom/TF-Essentials#7]
If you enable the permission to use colorcodes in chat, it will not work.

**Comment by JeromSar** [comment]
Please explain, I don't quite understand.

**Comment by aokod** [comment]
In the Essentials configuration, there is an option to enable usage of color codes in chat. For example, "&btest" would appear as blue in chat. It does not work for some reason.

**Comment by JeromSar** [comment]
@ShadowArmadyl That is a configuration option for EssentialsChat. EssentialsChat is not present on the server.
