### ISSUE TITLE
Limit /speed to 5

### ISSUE THREAD

**Issue by aggelosQQ** [TotalFreedom/TF-Essentials#8]
What about to limit the /speed command to 5, instead of 10? For non-admins or everyone?
@JeromSar 
To reduce the crashes caused from this command (http://totalfreedom.boards.net/thread/27637/server-crashing)

**Comment by CommissionerJoe** [comment]
Yep.. I'm aware of this also.

**Comment by JeromSar** [comment]
The ability to set this limit is actually already present in essentials. However, all OPs can bypass it. This will be prevented in the next release. Thanks for your suggestion! :)

**Comment by JeromSar** [comment]
Implemented in https://github.com/TotalFreedom/TF-Essentials/commit/baabed5047a8d5ad3e72e5db4c8248edc55c3343
